export enum FORGET_PASSWORD_SCREENS {
  SEND_RESET_CODE = "SEND_RESET_CODE",
  VERIFICATION_RESET_CODE = "VERIFICATION_RESET_CODE",
  CREATE_NEW_PASSWORD = "CREATE_NEW_PASSWORD",
}

export enum VERIFY_EMAIL_SCREENS {
  SEND_Email_CODE = "SEND_Email_CODE",
  VERIFICATION_Email_CODE = "VERIFICATION_Email_CODE",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
}
